name: Auto Sync Fork with Upstream

on:
  push:
    branches:
      - main
  workflow_dispatch: # 수동 실행 가능

jobs:
  sync:
    runs-on: ubuntu-latest
    if: github.event.repository.fork == true && github.repository == 'K-PaaS-Team22/shelter-web'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Git
        run: |
          git config --global user.name "Auto Sync Bot"
          git config --global user.email "auto-sync@github.com"

      - name: Add upstream remote
        run: |
          git remote add upstream https://github.com/${{ github.event.repository.parent.full_name || github.repository_owner }}/${{ github.event.repository.name }}.git
          git fetch upstream

      - name: Sync main branch
        run: |
          git checkout main
          git merge upstream/main --no-edit

          # 변경사항이 있으면 푸시
          if ! git diff --quiet HEAD~1 HEAD; then
            git push origin main
            echo "✅ Successfully synced with upstream"
          else
            echo "ℹ️ Already up to date"
          fi

      - name: Sync other branches (optional)
        run: |
          # develop 브랜치가 있다면 싱크
          if git show-ref --verify --quiet refs/remotes/upstream/develop; then
            if git show-ref --verify --quiet refs/heads/develop; then
              git checkout develop
              git merge upstream/develop --no-edit
              git push origin develop
              echo "✅ develop 브랜치 싱크 완료"
            else
              git checkout -b develop upstream/develop
              git push origin develop
              echo "✅ develop 브랜치 생성 및 싱크 완료"
            fi
          else
            echo "ℹ️ upstream에 develop 브랜치가 없습니다"
          fi

      - name: Sync summary
        run: |
          echo "🎉 포크 싱크 작업 완료!"
          echo "📅 완료 시간: $(date)"
          echo "🔄 마지막 커밋: $(git log -1 --pretty=format:'%h - %s (%an, %ar)')"
