name: 포크 자동 싱크

on:
  workflow_dispatch:          # 수동 실행 가능
  push:
    branches: [ main ]        # 내 포크 main에 push 될 때도 실행

permissions:
  contents: write             # push 권한 필요

jobs:
  sync:
    runs-on: ubuntu-latest
    if: ${{ github.event.repository.fork == true }}

    steps:
      - name: 리포지토리 체크아웃
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Git 설정
        run: |
          git config --global user.name "자동 싱크 봇"
          git config --global user.email "auto-sync@github.com"

      - name: upstream 원본 추가
        run: |
          UPSTREAM="${{ github.event.repository.parent.full_name }}"
          if [ -z "$UPSTREAM" ]; then
            echo "❌ 원본 저장소(parent)를 찾을 수 없습니다. 포크가 맞나요?"
            exit 1
          fi
          git remote add upstream "https://github.com/$UPSTREAM.git"
          git fetch upstream --prune

      - name: main 브랜치 싱크
        run: |
          git checkout main
          git merge upstream/main --no-edit || exit 1

          if ! git diff --quiet origin/main..HEAD; then
            git push origin main
            echo "✅ main 브랜치가 원본과 동기화되었습니다."
          else
            echo "ℹ️ main 브랜치는 이미 최신 상태입니다."
          fi

      - name: develop 브랜치 싱크 (선택)
        run: |
          if git show-ref --verify --quiet refs/remotes/upstream/develop; then
            if git show-ref --verify --quiet refs/heads/develop; then
              git checkout develop
              git merge upstream/develop --no-edit || exit 1
            else
              git checkout -b develop upstream/develop
            fi

            if ! git diff --quiet origin/develop..HEAD; then
              git push origin develop
              echo "✅ develop 브랜치가 원본과 동기화되었습니다."
            else
              echo "ℹ️ develop 브랜치는 이미 최신 상태입니다."
            fi
          else
            echo "ℹ️ 원본 저장소에는 develop 브랜치가 없습니다."
          fi

      - name: 요약
        run: |
          echo "🎉 포크 싱크 완료!"
          echo "📅 완료 시각: $(date)"
          echo "🔄 마지막 커밋: $(git log -1 --pretty=format:'%h - %s (%an, %ar)')"
