name: Notify forks to sync

on:
  push:
    branches: [ main ]   

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: repository_dispatch
        env:
          GH_TOKEN: ${{ secrets.FORK_DISPATCH_TOKEN }}
          FORK_OWNER: hyun907
          FORK_REPO: shelter-web
        run: |
          curl -s -X POST \
            -H "Authorization: token $GH_TOKEN" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/$FORK_OWNER/$FORK_REPO/dispatches \
            -d '{"event_type":"upstream-updated","client_payload":{"branch":"main"}}'
