name: Sync Fork on Upstream Update

on:
  repository_dispatch:
    types: [upstream-updated]

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout fork
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set Git Identity
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - name: Add upstream
        run: |
          git remote add upstream https://github.com/K-PaaS-Team22/shelter-web.git

      - name: Fetch upstream
        run: git fetch upstream

      - name: Merge upstream/main into fork main
        run: |
          git checkout main
          git merge --no-edit upstream/main

      - name: Push to origin
        run: git push origin main
